#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

echo "Removing old build..."
rm -rfv /opt/firestorm/* | pv -l -s $( du -a "/opt/firestorm/" | wc -l ) > /dev/null

echo "Copying new build..."
cp -rv "$DIR/phoenix-firestorm-lgpl/build-linux-x86_64/newview/packaged/." "/opt/firestorm/" | pv -l -s $( du -a "$DIR/phoenix-firestorm-lgpl/build-linux-x86_64/newview/packaged" | wc -l ) > /dev/null
